# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My tech blog
email: david.saenz.tagarro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A box to place snippets of code. My day to day little tricks :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dsaenztagarro
github_username: dsaenztagarro

# Build settings
markdown: kramdown
